---
- name: Prepare EC2 server
  hosts: webservers
  become: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install python and required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
